### ISSUE TITLE
Missing requirement

### ISSUE THREAD

**Issue by florin-rada** [logchange/SecScanner2JUnit#42]
**Describe the bug**
On a clean python3.12 install, after installing SecScanner2JUnit through the command `python3 -m pip install SecScanner2Junit` , executing ss2ju script fails due to missing pkg_resources package which is imported in SecScanner2JUnit/__init__.py file.
This package is added by setuptools.

**Steps to reproduce**

1. Install python3 version 3.10 or higher
2. execute `ss2ju sast gl-sast-semgrep-report.json gl-sast-semgrep-report.xml`
3. Receive error below:
`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python3\Scripts\ss2ju.exe\__main__.py", line 4, in <module>
  File "C:\Python3\Lib\site-packages\secscanner2junit\__init__.py", line 5, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'`

**Expected behavior**
The generation of gl-sast-semgrep-report.xml file

**Additional context/Screenshots**
I was able to solve this issue by executing
python3 -m pip install --upgrade setuptools
Maybe adding setuptools to the [tool.poetry.dependencies] in pyproject.toml

**Comment by marwin1991** [comment]
@florin-rada fixed :)
