### ISSUE TITLE
Support DependencyCheck GitLab outpuit

### ISSUE THREAD

**Issue by marwin1991** [logchange/SecScanner2JUnit#43]
**Describe the idea**
- DependencyCheck has JUNIT format, but output of this is not compatible with output of  [SecScanner2JUnit](https://github.com/angrymeir/SecScanner2JUnit), 
- DependencyCheck has option to produce GitLab format .json file format
![image](https://github.com/angrymeir/SecScanner2JUnit/assets/25181517/0b48f25e-56be-4b5e-9633-daf14f9c5ad7)
https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html

It should work like sast's but now is failling, I will provide some file to test on it :)

**Comment by marwin1991** [comment]
```
$ ss2ju sast target/dependency-check-gitlab.json maven-dependency-check-gitlab.xml .gitlab/ss2ju-config.yml
Traceback (most recent call last):
  File "/usr/local/bin/ss2ju", line 8, in <module>
No config found at path: .gitlab/ss2ju-config.yml
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/secscanner2junit/__init__.py", line 63, in main
    testsuite = parser.parse()
                ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/secscanner2junit/sast.py", line 32, in parse
    scanners = list(set(vuln['scanner']['name'] for vuln in vulnerabilities))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/secscanner2junit/sast.py", line 32, in <genexpr>
    scanners = list(set(vuln['scanner']['name'] for vuln in vulnerabilities))
                        ~~~~^^^^^^^^^^^
KeyError: 'scanner'
```
